name: Update Version

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Current version: $VERSION"
          echo "::set-output name=CURRENT_VERSION::$VERSION"

      - name: Get change type
        id: get_change_type
        run: |
          CHANGE_TYPE=$(head -n 1 changes.md)
          echo "Change type: $CHANGE_TYPE"
          echo "change-type=$CHANGE_TYPE" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          CHANGE_TYPE=${{ env.change-type }}
          echo "Change type: $CHANGE_TYPE"
          
          # Configure npm to not use the "v" prefix.
          npm config set tag-version-prefix ""
          
          # Check Git status for debugging
          git status
          
          # Ensure Git configuration is set
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Attempt to update the version with verbose output
          case $CHANGE_TYPE in
            "patch")
              NEW_VERSION=$(npm version patch --silent --no-git-tag-version)
              ;;
            "minor")
              NEW_VERSION=$(npm version minor --silent --no-git-tag-version)
              ;;
            "major")
              NEW_VERSION=$(npm version major --silent --no-git-tag-version)
              ;;
            *)
              echo "Invalid change type in changes.md"
              exit 1
              ;;
          esac
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update package.json file
        run: |
          jq --arg VERSION "$NEW_VERSION" '.version = $VERSION' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Update CHANGELOG.md
        run: |
          DATE=$(date +%Y-%m-%d)
          # Save the current content of CHANGELOG.md
          cp CHANGELOG.md CHANGELOG.tmp
          # Add the new version heading to CHANGELOG.md
          echo "# $NEW_VERSION ($DATE)" > CHANGELOG.md
          # Append the content of changes.md without the first line
          tail -n +2 changes.md >> CHANGELOG.md
          # Add an extra newline for spacing
          echo "" >> CHANGELOG.md
          # Append the previous content of CHANGELOG.md
          cat CHANGELOG.tmp >> CHANGELOG.md
          # Remove the temporary file
          rm CHANGELOG.tmp

      - name: Delete changes.md
        run: git rm changes.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json CHANGELOG.md
          git commit -m "Update version to $NEW_VERSION"

      - name: Push changes
        run: git push origin master

